{
 "title": "App monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"app\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"app\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"app\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"app\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"app\", resource=\"limits\"}\n)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"app\", container=\"app\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}